# -*- coding: utf-8 -*-
# **************************************************************************
# *
# * Authors:     Scipion Team
# *
# * National Center of Biotechnology, CSIC, Spain
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
from enum import Enum
from os.path import join

import mrcfile
import numpy as np

from gapstop import Plugin
from gapstop.constants import *
from gapstop.protocols.protocol_base import ProtGapStopBase
from pwem.convert import transformations
from pyworkflow import BETA
from pyworkflow.object import Set
from pyworkflow.protocol import PointerParam, IntParam, FloatParam, GT, STEPS_PARALLEL, LE, GE
from pyworkflow.utils import Message, makePath
from scipion.constants import PYTHON
from tomo.constants import BOTTOM_LEFT_CORNER
from tomo.objects import SetOfCoordinates3D, Tomogram, Coordinate3D, SetOfTomograms, SetOfTomoMasks
from tomo.utils import getObjFromRelation


class GSExtractCoordsOutputs(Enum):
    coordinates = SetOfCoordinates3D


class ProtGapStopExtractCoords(ProtGapStopBase):
    """
    Extracts coordinates from score maps produced by template matching with GAPSTOP(TM).

    AI Generated:

    GapStop Extract Coordinates (ProtGapStopExtractCoords) - User Manual
        Overview

        The GapStop Extract Coordinates protocol identifies candidate particle
        positions from score tomograms generated during template matching in
        cryo-electron tomography workflows. Its purpose is to convert dense
        correlation maps into biologically meaningful particle coordinates that
        can later be used for subtomogram extraction, classification, averaging,
        or structural interpretation.

        In practical cryo-ET analysis, template matching produces volumetric
        score maps where higher values indicate regions that resemble the input
        reference structure. However, these maps alone are not directly useful
        for downstream structural workflows. This protocol transforms those
        response maps into discrete particle locations and orientations,
        allowing users to move from detection to structural analysis.

        For biological users, this step represents the transition between
        searching for macromolecular complexes inside tomograms and building
        curated particle datasets suitable for subtomogram averaging or in situ
        structural studies. The quality of the extracted coordinates strongly
        influences all downstream analyses.

        Inputs and General Workflow

        The protocol requires score tomograms generated by the GAPSTOP template
        matching workflow. These tomograms contain both correlation scores and
        orientation information describing how well the reference matches each
        location in the reconstructed volume.

        The extraction process identifies local high-scoring regions and
        converts them into candidate particle coordinates. Each detected
        particle preserves not only its spatial position but also its estimated
        orientation, allowing subsequent subtomogram workflows to initialize
        particles in biologically relevant poses.

        The protocol is designed for large tomographic datasets and can process
        multiple tomograms independently. This makes it suitable for
        high-throughput cryo-ET studies where hundreds or thousands of particle
        candidates may be detected across many cellular volumes.

        Particle Diameter and Clustering Behavior

        One of the most important biological parameters is the particle
        diameter. This value defines the effective spatial scale used to
        separate neighboring detections and cluster nearby responses into
        individual particle candidates.

        Biologically, the parameter should approximately reflect the expected
        size of the target complex inside the tomogram. Choosing an excessively
        small value may produce many redundant detections around the same
        structure, while an excessively large value may merge neighboring
        particles or suppress legitimate detections in crowded environments.

        In dense cellular tomograms, careful tuning of the particle diameter is
        particularly important because macromolecular assemblies may appear
        closely packed or partially overlapping. Flexible or elongated
        structures may also require practical compromises between strict
        geometric interpretation and robust detection behavior.

        Score Thresholding and Percentile Selection

        The protocol selects candidate particles according to score intensity
        within the template matching map. Instead of relying on an absolute
        numerical threshold, extraction is guided by percentile values.

        This approach is biologically useful because score distributions often
        vary substantially between tomograms depending on ice thickness,
        reconstruction quality, contrast transfer effects, and molecular crowding.
        Percentile-based selection adapts more naturally to heterogeneous data.

        High percentile values generally produce cleaner particle sets with
        fewer false positives, making them suitable for high-confidence
        structural studies. Lower percentile values increase sensitivity and
        may recover weaker or partially occupied particles, although at the
        cost of introducing additional noise and spurious detections.

        In exploratory workflows, users commonly begin with permissive
        thresholds to inspect the distribution of candidates and later tighten
        the percentile for more rigorous analyses. Biological validation by
        visual inspection remains essential, especially in crowded cellular
        environments.

        Limiting the Number of Coordinates

        The protocol optionally allows restricting the number of extracted
        coordinates per tomogram. This is particularly useful during rapid
        exploratory analyses, parameter optimization, or computationally
        intensive downstream workflows.

        In many biological studies, selecting only the highest-scoring
        candidates provides a practical way to focus on the most reliable
        particles before investing resources in subtomogram extraction or
        refinement. However, aggressive filtering may remove biologically
        meaningful low-abundance or conformationally variable complexes.

        For heterogeneous datasets, retaining a broader set of candidates is
        often preferable during early stages of analysis, followed by later
        cleaning through classification and averaging procedures.

        Tomogram Masks and Spatial Restriction

        The protocol supports optional tomogram masks that restrict extraction
        to biologically relevant regions of the reconstructed volume. This is
        especially important in cellular cryo-ET studies where only specific
        compartments, membranes, organelles, or subcellular regions are of
        interest.

        Applying masks can significantly reduce false positives originating
        from reconstruction artifacts, empty solvent regions, carbon support,
        or unrelated cellular material. From a biological perspective, masking
        allows the analysis to focus specifically on the structural context of
        interest.

        Accurate correspondence between masks and tomograms is essential.
        Misaligned masks may exclude valid particles or introduce strong spatial
        biases into the resulting dataset.

        Orientation Information and Structural Context

        Beyond particle positions, the protocol also preserves orientation
        information derived from template matching. This orientation assignment
        is highly valuable for subtomogram averaging workflows because it
        provides meaningful initial alignment parameters.

        In biological applications involving membrane proteins, viral lattices,
        cytoskeletal assemblies, or ordered cellular structures, reliable
        orientation estimation can substantially improve convergence during
        refinement. Even approximate angular assignments may reduce alignment
        ambiguity and accelerate downstream processing.

        Nevertheless, biological users should remember that template-derived
        orientations depend strongly on the quality and representativeness of
        the reference structure. Flexible particles, partially occupied states,
        or strong missing-wedge artifacts may reduce angular reliability.

        Outputs and Their Interpretation

        The protocol produces a set of 3D particle coordinates associated with
        the original tomograms. Each coordinate contains positional information,
        orientation parameters, and a score describing the quality of the
        template match.

        These coordinates can be directly used for subtomogram extraction,
        averaging pipelines, visualization, or further particle cleaning.
        Biologically, the resulting dataset represents a hypothesis about the
        spatial distribution and organization of the target complex inside the
        specimen.

        High-scoring particles often correspond to well-resolved and abundant
        structures, whereas lower-scoring detections may reflect structural
        variability, partial occupancy, or false positives. Careful downstream
        validation is therefore essential before biological interpretation.

        Practical Recommendations

        For most biological workflows, it is advisable to begin with moderately
        strict percentile thresholds and visually inspect the resulting
        coordinates in the tomographic context. If too many false positives are
        observed, increasing the percentile or introducing tomogram masks
        usually provides the largest improvement.

        Particle diameter should be adjusted according to the expected size and
        packing density of the biological target. Dense cellular environments
        often require iterative tuning to balance sensitivity and specificity.

        When studying rare or heterogeneous complexes, users may benefit from
        extracting a larger set of candidates initially and relying on later
        classification steps to separate true particles from noise.

        Final Perspective

        Coordinate extraction is not merely a technical conversion of score
        maps into particle lists. In cryo-electron tomography, it defines the
        candidate structural population that will shape all downstream
        biological interpretation. Appropriate thresholding, biologically
        informed masking, and careful validation of extracted particles are
        essential for obtaining reliable in situ structural insights.
    """

    _label = 'extract coordinates'
    _devStatus = BETA
    _possibleOutputs = GSExtractCoordsOutputs
    stepsExecutionMode = STEPS_PARALLEL

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.scoreTomoDict = None
        self.tomoSet = None
        self.tomoMasksDict = None

    # --------------------------- DEFINE param functions ----------------------
    def _defineParams(self, form):
        form.addSection(label=Message.LABEL_INPUT)
        form.addParam(IN_SCORE_TOMOS, PointerParam,
                      pointerClass='SetOfGapStopScoreTomograms',
                      important=True,
                      label='Score tomograms',
                      help='They are the result of the gapstop template matching.')
        form.addParam('partDiameter', FloatParam,
                      default=10,
                      important=True,
                      validators=[GT(0)],
                      label='Particle diameter (px)',
                      help='Diameter of the particle to be used for extraction and clustering.\n\n'
                           'In this context, it has more correspondence with a mathematical '
                           'representation than with the exact physical diameter of the particle. '
                           'It is a way to establish a distance criterion for the search and clustering '
                           'of points in the correlation map. In a tomogram, particles may not be '
                           'perfectly spherical, and their diameters may vary. By using a value for '
                           'the "particle diameter," you are defining a distance threshold that is '
                           'useful for identifying and grouping points that are likely to belong to '
                           'the same particle or structure in the score map.\n\n'
                           'In some contexts, the density of points in the score map may vary. '
                           'A smaller diameter can reduce noise by focusing on more compact groups, '
                           'while in other cases, a larger diameter may be necessary to cluster '
                           'larger and more spaced-out particles.')
        form.addParam('percentile', FloatParam,
                      default=99.5,
                      important=True,
                      validators=[GE(0), LE(100)],
                      label='Percentile value',
                      help='Percentile value [in range [0, 100] of the GapStopScoreTomograms that will be used '
                           'to determine the best candidates to be particles. If a max. number of coordinates '
                           'per tomogram is provided, they will be the best N decending sorted by score. Normally, '
                           'the recommended values are from 99.5 to 99.99.')
        form.addParam('numberOfCoords', IntParam,
                      default=-1,
                      label='Max no. coordinates per tomogram',
                      help='If set to -1, all the coordinates resulting after having applied the particle diameter '
                           'and the score threshold will be saved. Any other case, the first N coordinates, sorted '
                           'by score, will be saved.')
        form.addParam(IN_TOMO_MASKS, PointerParam,
                      pointerClass='SetOfTomoMasks',
                      allowsNull=True,
                      label='Tomogram masks (opt.)',
                      help='Optional set of tomogram masks. If provided, coordinates will only be extracted '
                           'from regions where the mask value is non-zero. Each mask should correspond to a '
                           'tomogram by its tsId.')
        form.addParallelSection(threads=1, mpi=0)

    # --------------------------- INSERT steps functions ----------------------
    def _insertAllSteps(self):
        self._initialize()
        closeSetStepDeps = []
        for tsId in self.scoreTomoDict:
            ecId = self._insertFunctionStep(self.extractCoordinatesStep, tsId,
                                            prerequisites=[],
                                            needsGPU=False)
            cOutId = self._insertFunctionStep(self.createOutputStep, tsId,
                                              prerequisites=ecId,
                                              needsGPU=False)
            closeSetStepDeps.append(cOutId)
        self._insertFunctionStep(self._closeOutputSet,
                                 prerequisites=closeSetStepDeps,
                                 needsGPU=False)

    # -------------------------- STEPS functions ------------------------------
    def _initialize(self):
        scoreTomoSet = self._getFormAttrib(IN_SCORE_TOMOS)
        self.scoreTomoDict = {sTomo.getTsId(): sTomo.clone() for sTomo in scoreTomoSet.iterItems()}
        self.tomoSet = self._getTomosFromRelations()
        # Initialize tomo masks dictionary if provided
        tomoMasksSet = self._getFormAttrib(IN_TOMO_MASKS)
        if tomoMasksSet:
            self.tomoMasksDict = {tomoMask.getTsId(): tomoMask.clone() for tomoMask in tomoMasksSet.iterItems()}
        else:
            self.tomoMasksDict = {}

    def extractCoordinatesStep(self, tsId: str):
        sTomo = self.scoreTomoDict[tsId]
        tsIdExtraDir = self._getCurrentTomoDir(tsId)
        makePath(tsIdExtraDir)
        outParticleListFile = self._getTsIdExtraDirFile(tsId, PARTICLE_LIST_FILE)
        scoresMap = sTomo.getFileName()
        # Get tomo_mask path if available for this tsId
        tomoMaskPath = self._getTomoMaskPath(tsId)
        # scores_threshold = {self.scoresThreshold.get()},
        codePatch = f"""
from cryocat import tmana        

tmana.scores_extract_particles(
scores_map='{scoresMap}',
angles_map='{sTomo.getAnglesMap()}',
angles_list='{sTomo.getAngleList()}',
tomo_id={sTomo.getTomoNum()},
particle_diameter={self.partDiameter.get()},
object_id=None,
scores_threshold={self._getScorePercentileValue(scoresMap)},
sigma_threshold=None,
cluster_size=None,
n_particles=None,
output_path='{outParticleListFile}',
output_type='emmotl',
angles_order='zxz',
symmetry='{sTomo.getSymmetry()}',
angles_numbering=0,
tomo_mask={tomoMaskPath})
"""
        extractCoordsPythonFile = join(tsIdExtraDir, 'extractCoords.py')
        with open(extractCoordsPythonFile, "w") as pyFile:
            pyFile.write(codePatch)
        Plugin.runGapStop(self, PYTHON, extractCoordsPythonFile, isCryoCatExec=True)

    def createOutputStep(self, tsId: str):
        with self._lock:
            outCoords = self.createOutputSet()
            # The particle list is encoded in a .em file. Thus, it will be loaded and decoded.
            particlesDataNpyFile = self._loadParticleList(tsId)
            particlesData = np.load(particlesDataNpyFile)
            tomo = self.tomoSet.getItem(Tomogram.TS_ID_FIELD, tsId)
            for row in particlesData:
                coord = self._createCoordFromRow(tomo, row)
                outCoords.append(coord)
            outCoords.write()
            self._store(outCoords)

    # --------------------------- UTILS functions -----------------------------
    def createOutputSet(self):
        outCoords = getattr(self, self._possibleOutputs.coordinates.name, None)
        if outCoords:
            outCoords.enableAppend()
        else:
            inScoreTomosPointer = self._getFormAttrib(IN_SCORE_TOMOS, returnPointer=True)
            inScoreTomos = inScoreTomosPointer.get()
            outCoords = SetOfCoordinates3D.create(self._getPath(), template="coordinates%s")
            outCoords.setPrecedents(self.tomoSet)
            outCoords.setSamplingRate(inScoreTomos.getSamplingRate())
            outCoords.setBoxSize(self.partDiameter.get())
            outCoords.setStreamState(Set.STREAM_OPEN)

            self._defineOutputs(**{self._possibleOutputs.coordinates.name: outCoords})
            self._defineSourceRelation(inScoreTomosPointer, outCoords)

        return outCoords

    def _getTomosFromRelations(self) -> SetOfTomograms:
        inScoreTomos = self._getFormAttrib(IN_SCORE_TOMOS)
        return getObjFromRelation(inScoreTomos, self, SetOfTomograms)

    def _getTomoMaskPath(self, tsId: str) -> str:
        """Returns the tomo mask path for a given tsId, or None if not available.
        The return value is formatted as a string for use in generated Python code."""
        if self.tomoMasksDict and tsId in self.tomoMasksDict:
            maskPath = self.tomoMasksDict[tsId].getFileName()
            return f"'{maskPath}'"
        return 'None'

    def _getScorePercentileValue(self, tomoFileName: str) -> float:
        with mrcfile.mmap(tomoFileName) as mrc:
            data = mrc.data
            percentileVal = np.percentile(data, self.percentile.get())
            return percentileVal


    def _loadParticleList(self, tsId: str) -> str:
        """The particle list is encoded in a .em file. Thus, it will be loaded and decoded. The data represented
        on each column is explained in https://cryocat.readthedocs.io/latest/user_guide/motl_basics.html"""
        particlesEmFile = self._getTsIdExtraDirFile(tsId, PARTICLE_LIST_FILE)
        outParticlesNpyFile = self._getTsIdExtraDirFile(tsId, PARTICLES_DATA_FILE, NPY)
        maxNumCoords = self.numberOfCoords.get()
        codePatch = f""" 
import emfile 
import numpy as np

_, data = emfile.read('{particlesEmFile}')
# Use numpy.squeeze() to remove dimensions of size 1 
data = np.squeeze(data)
# Save the first N particles, knowing that they are sorted descending by score
if {maxNumCoords} > -1 and data.shape[0] > {maxNumCoords}:
    data = data[0:{maxNumCoords}, :]
np.save('{outParticlesNpyFile}', data)
        """
        readEmParticlePythonFile = join(self._getCurrentTomoDir(tsId), 'readEmParticles.py')
        with open(readEmParticlePythonFile, "w") as pyFile:
            pyFile.write(codePatch)
        Plugin.runGapStop(self, PYTHON, readEmParticlePythonFile, isCryoCatExec=True)
        return outParticlesNpyFile

    def _createCoordFromRow(self, tomo: Tomogram, row: np.array):
        """The particle list is encoded in a .em file. Thus, it will be loaded and decoded. The data represented
        on each column is explained in https://cryocat.readthedocs.io/latest/user_guide/motl_basics.html:
        Columns:
        0 - "score” - a quality metric (typically cross-correlation value between the particle and the reference)
        1 - "geom1” - a free geometric property
        2 - "geom2” - a free geometric property
        3 - "subtomo_id” - a subtomogram id; IMPORTANT many functions rely on this one to be unique
        4 - "tomo_id” - a tomogram id to which the particle is affiliated to
        5 - "object_id” - an object id to which the particle is affiliated to
        6 - "subtomo_mean” - a mean value of the subtomogram
        7 - "x” - a position in the tomogram (an integer value), typically used for subtomogram extraction
        8 - “y” - a position in the tomogram (an integer value), typically used for subtomogram extraction
        9 - “z” - a position in the tomogram (an integer value), typically used for subtomogram extraction
        10 - “shift_x” - shift of the particle in X direction (a float value); to complete position of a particle is given by x + shift_x
        11 - “shift_y” - shift of the particle in Y direction (a float value); to complete position of a particle is given by y + shift_y
        12 - “shift_z” - shift of the particle in Z direction (a float value); to complete position of a particle is given by z + shift_z
        13 - “geom3” - a free geometric property
        14 - “geom4” - a free geometric property
        15 - “geom5” - a free geometric property
        16 - “phi” - a phi angle describing rotation around the first Z axis (following Euler zxz convention)
        17 - “psi” - a psi angle describing rotation around the second Z axis (following Euler zxz convention)
        18 - “theta” - a thetha angle describing rotation around the X axis (following Euler zxz convention)
        19 - “class” - a class of the particle"""
        coord = Coordinate3D()
        score = row[0]
        x, y, z = row[7:10]
        sx, sy, sz = row[10:13]
        phi, psi, theta = row[16:19]
        matrix = self.eulerAngles2matrix(phi, theta, psi, sx, sy, sz)
        coord.setScore(score)
        coord.setVolume(tomo)
        coord.setPosition(x, y, z, BOTTOM_LEFT_CORNER)
        coord.setMatrix(matrix)
        return coord

    @staticmethod
    def eulerAngles2matrix(tdrot, tilt, narot, shiftx, shifty, shiftz):
        # Relevant info:
        #   * GapStop's transformation system is ZXZ
        #   * Sscipion = R * (-Sgapstop) ==> Sgapstop = Rinv * (-Sscipion)
        M = np.eye(4)
        sx = float(shiftx)
        sy = float(shifty)
        sz = float(shiftz)
        Sgapstop = np.array([sx, sy, sz])
        tdrot = np.deg2rad(float(tdrot))
        narot = np.deg2rad(float(narot))
        tilt = np.deg2rad(float(tilt))
        R = transformations.euler_matrix(tdrot, tilt, narot, axes='szxz')
        R = R[:3, :3]
        Sscipion = - np.dot(R, Sgapstop)
        M[:3, :3] = R
        M[:3, 3] = Sscipion
        return M
