# -*- coding: utf-8 -*-
# **************************************************************************
# *
# * Authors:     Scipion Team
# *
# * National Center of Biotechnology, CSIC, Spain
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
from pyworkflow.object import String, Integer, Pointer
from tomo.objects import Tomogram, SetOfTomograms


class ScoreTomogram(Tomogram):
    """ Object used to represent scored tomograms generated by gapstop_tm."""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._scoresMap = String()  # Path to the corresponding tomogram
        self._anglesMap = String()  # Path to the angles map file generated by gapstop_tm
        self._angleList = String()  # Path to the angles list file generated by gapstop_tm
        self._tomoNum = Integer()  # Numeric id required by gapstop_tm
        self._symmetry = String()

    def setAnglesMap(self, val: str):
        self._anglesMap.set(val)

    def setAnglesList(self, val: str):
        self._angleList.set(val)

    def setTomoNum(self, val: int):
        self._tomoNum.set(val)

    def setSymmetry(self, val: str):
        self._symmetry.set(val)

    def setScoresMap(self, val: str):
        self._scoresMap.set(val)

    def getAnglesMap(self):
        return self._anglesMap.get()

    def getAngleList(self):
        return self._angleList.get()

    def getTomoNum(self):
        return self._tomoNum.get()

    def getSymmetry(self):
        return self._symmetry.get()

    def getScoresMap(self):
        return self._scoresMap.get()


class SetOfScoreTomograms(SetOfTomograms):
    ITEM_TYPE = ScoreTomogram
    EXPOSE_ITEMS = True

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._precedentsPointer = Pointer()  # Pointer to the corresponding SetOfTomograms

    def setPrecedents(self, precedents):
        if precedents.isPointer():
            self._precedentsPointer.copy(precedents)
        else:
            self._precedentsPointer.set(precedents)

    def getPrecedents(self):
        return self._precedentsPointer.get()
